export const assets = {
  audio: [
    { name: 'cheer', path: 'assets/sounds/cheer.wav' },
    { name: 'hah-1', path: 'assets/sounds/hah-1.wav' },
    { name: 'hah-2', path: 'assets/sounds/hah-1.ogg'},
    { name: 'hah-3', path: 'assets/sounds/hah-2.wav' },
    { name: 'heh-1', path: 'assets/sounds/heh-1.ogg' },
    { name: 'huh-1', path: 'assets/sounds/huh-1.ogg'},
    { name: 'mumble-1', path: 'assets/sounds/mumble-1.wav' },
    { name: 'mumble-2', path: 'assets/sounds/mumble-2.wav' },
    { name: 'mumble-3', path: 'assets/sounds/mumble-3.wav' },
    { name: 'mumble-4', path: 'assets/sounds/mumble-4.wav' },
    { name: 'music', path: 'assets/sounds/music.wav' },
  ],
  images: [
    { name: 'background', path: 'assets/background/background.png' },
    { name: 'blue-1', path: 'assets/people/blue-1.png' },
    { name: 'blue-2', path: 'assets/people/blue-2.png' },
    { name: 'button-red', path: 'assets/buttons/red.png' },
    { name: 'button-blue', path: 'assets/buttons/blue.png' },
    { name: 'button-yellow', path: 'assets/buttons/yellow.png' },
    { name: 'button-green', path: 'assets/buttons/green.png' },
    { name: 'chair', path: 'assets/background/chair-l.png' },
    { name: 'dino-1', path: 'assets/dino/dino-1.png' },
    { name: 'dino-2', path: 'assets/dino/dino-2.png' },
    { name: 'dino-3', path: 'assets/dino/dino-3.png' },
    { name: 'dino-4', path: 'assets/dino/dino-4.png' },
    { name: 'dino-5', path: 'assets/dino/dino-5.png' },
    { name: 'dino-6', path: 'assets/dino/dino-6.png' },
    { name: 'dino-7', path: 'assets/dino/dino-7.png' },
    { name: 'dino-8', path: 'assets/dino/dino-8.png' },
    { name: 'dino-9', path: 'assets/dino/dino-9.png' },
    { name: 'green-1', path: 'assets/people/green-1.png' },
    { name: 'lights', path: 'assets/background/lights.png' },
    { name: 'logo', path: 'assets/logo.jpg' },
    { name: 'purple-1', path: 'assets/people/purple-1.png' },
    { name: 'purple-2', path: 'assets/people/purple-2.png' },
    { name: 'red-1', path: 'assets/people/red-1.png' },
    { name: 'red-2', path: 'assets/people/red-2.png' },
    { name: 'row-1', path: 'assets/background/row-1.png' },
    { name: 'row-2', path: 'assets/background/row-2.png' },
    { name: 'row-3', path: 'assets/background/row-3.png' },
    { name: 'row-4', path: 'assets/background/row-4.png' },
    { name: 'row-5', path: 'assets/background/row-5.png' },
    { name: 'row-6', path: 'assets/background/row-6.png' },
    { name: 'row-7', path: 'assets/background/row-7.png' },
    { name: 'row-8', path: 'assets/background/row-8.png' },
    { name: 'stage', path: 'assets/stage.jpg' },
    { name: 'yellow-1', path: 'assets/people/yellow-1.png' },
    { name: 'yellow-2', path: 'assets/people/yellow-2.png' },
  ],
};
