export const assets = [
  { name: 'background', path: 'assets/background/background.png' },
  { name: 'blue-1', path: 'assets/people/blue-1.png' },
  { name: 'blue-2', path: 'assets/people/blue-2.png' },
  { name: 'green-1', path: 'assets/people/green-1.png' },
  { name: 'purple-1', path: 'assets/people/purple-1.png' },
  { name: 'purple-2', path: 'assets/people/purple-2.png' },
  { name: 'red-1', path: 'assets/people/red-1.png' },
  { name: 'red-2', path: 'assets/people/red-2.png' },
  { name: 'stage', path: 'assets/stage.png' },
  { name: 'yellow-1', path: 'assets/people/yellow-1.png' },
  { name: 'yellow-2', path: 'assets/people/yellow-2.png' },
  { name: 'button-red', path: 'assets/buttons/red.png' },
  { name: 'button-blue', path: 'assets/buttons/blue.png' },
  { name: 'button-yellow', path: 'assets/buttons/yellow.png' },
  { name: 'button-green', path: 'assets/buttons/green.png' },
  { name: 'dino-1', path: 'assets/dino/dino-1.png' },
  { name: 'dino-2', path: 'assets/dino/dino-2.png' },
  { name: 'dino-3', path: 'assets/dino/dino-3.png' },
  { name: 'dino-4', path: 'assets/dino/dino-4.png' },
  { name: 'dino-5', path: 'assets/dino/dino-5.png' },
  { name: 'dino-6', path: 'assets/dino/dino-6.png' },
  { name: 'dino-7', path: 'assets/dino/dino-7.png' },
  { name: 'dino-8', path: 'assets/dino/dino-8.png' },
  { name: 'dino-9', path: 'assets/dino/dino-9.png' },
];
