export const assets = [
  { name: 'background', path: 'assets/background/background.png' },
  { name: 'blue-1', path: 'assets/people/blue-1.png' },
  { name: 'blue-2', path: 'assets/people/blue-2.png' },
  { name: 'green-1', path: 'assets/people/green-1.png' },
  { name: 'purple-1', path: 'assets/people/purple-1.png' },
  { name: 'purple-2', path: 'assets/people/purple-2.png' },
  { name: 'red-1', path: 'assets/people/red-1.png' },
  { name: 'red-2', path: 'assets/people/red-2.png' },
  { name: 'stage', path: 'assets/stage.png' },
  { name: 'yellow-1', path: 'assets/people/yellow-1.png' },
  { name: 'yellow-2', path: 'assets/people/yellow-2.png' },
  { name: 'button-red', path: 'assets/buttons/red.png' },
  { name: 'button-blue', path: 'assets/buttons/blue.png' },
  { name: 'button-yellow', path: 'assets/buttons/yellow.png' },
  { name: 'button-green', path: 'assets/buttons/green.png' },
];
